/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Define this if your regexec() function segfaults when passed an empty
   string under certain conditions. */
/* #undef BROKEN_REGEXEC */

/* Define this to enable nano debug messages and assert warnings. */
/* #undef DEBUG */

/* Define this to disable the built-in (crappy) file browser. */
/* #undef DISABLE_BROWSER */

/* Define this to disable the ^G help menu. */
#define DISABLE_HELP 1

/* Define this to disable the justify routine. */
/* #undef DISABLE_JUSTIFY */

/* Define this to disable the mouse functions. */
/* #undef DISABLE_MOUSE */

/* Define this to disable setting of the operating directory (chroot of
   sorts). */
#define DISABLE_OPERATINGDIR 1

/* Define this to disable wrapping as root by default. */
/* #undef DISABLE_ROOTWRAP */

/* Define this to disable the use(full|less) spelling functions. */
#define DISABLE_SPELLER 1

/* Define to disable the tab completion code Chris worked so hard on! */
#define DISABLE_TABCOMP 1

/* Define this to disable any and all text wrapping. */
/* #undef DISABLE_WRAPPING */

/* Define this to have syntax highlighting, requires ENABLE_NANORC too! */
#define ENABLE_COLOR 1

/* Define this to enable multiple file buffers. */
/* #undef ENABLE_MULTIBUFFER */

/* Define this to use the .nanorc file. */
#define ENABLE_NANORC 1

/* Define to 1 if translation of program messages to the user's native
   language is requested. */
/* #undef ENABLE_NLS */

/* Define to 1 if you have the <curses.h> header file. */
#define HAVE_CURSES_H 1

/* Define if the GNU dcgettext() function is already present or preinstalled.
   */
/* #undef HAVE_DCGETTEXT */

/* Define to 1 if you don't have `vprintf' but do have `_doprnt.' */
/* #undef HAVE_DOPRNT */

/* Define to 1 if you have the <fcntl.h> header file. */
#define HAVE_FCNTL_H 1

/* Define to 1 if you have the <getopt.h> header file. */
#define HAVE_GETOPT_H 1

/* Define to 1 if you have the `getopt_long' function. */
#define HAVE_GETOPT_LONG 1

/* Define if the GNU gettext() function is already present or preinstalled. */
/* #undef HAVE_GETTEXT */

/* Define if you have the iconv() function. */
/* #undef HAVE_ICONV */

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <libintl.h> header file. */
#define HAVE_LIBINTL_H 1

/* Define to 1 if you have the <limits.h> header file. */
#define HAVE_LIMITS_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <ncurses.h> header file. */
/* #define HAVE_NCURSES_H 1 */

/* Define to 1 if you have the <regex.h> header file. */
#define HAVE_REGEX_H 1

/* Define to 1 if you have the `snprintf' function. */
#define HAVE_SNPRINTF 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the `strcasecmp' function. */
#define HAVE_STRCASECMP 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the `strncasecmp' function. */
#define HAVE_STRNCASECMP 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <termios.h> header file. */
#define HAVE_TERMIOS_H 1

/* Define to 1 if you have the <termio.h> header file. */
#define HAVE_TERMIO_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define this if your curses lib has the _use_keypad flag. */
#define HAVE_USEKEYPAD 1

/* Define this if your curses library has the use_default_colors command. */
#define HAVE_USE_DEFAULT_COLORS 1

/* Define to 1 if you have the `vprintf' function. */
#define HAVE_VPRINTF 1

/* Define to 1 if you have the `vsnprintf' function. */
#define HAVE_VSNPRINTF 1

/* Define this to enable the extra stuff. */
/* #undef NANO_EXTRA */

/* Define this to make the nano executable as small as possible. */
/* #undef NANO_SMALL */
#define NANO_SMALL 1

/* Shut up the assert warnings :-) */
#define NDEBUG 1

/* Name of package */
#define PACKAGE "nano"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "nano-devel@gnu.org"

/* Define to the full name of this package. */
#define PACKAGE_NAME "GNU Nano"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "GNU Nano 1.2.5"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "nano"

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.2.5"

/* Define as the return type of signal handlers (`int' or `void'). */
#define RETSIGTYPE void

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define to use the slang wrappers for curses instead of native curses. */
/* #undef USE_SLANG */

/* Version number of package */
#define VERSION "1.2.5"

/* Number of bits in a file offset, on hosts where this is settable. */
#define _FILE_OFFSET_BITS 32
/*#undef _FILE_OFFSET_BITS*/

/* Define for large files, on AIX-style hosts. */
/* #undef _LARGE_FILES */
