#!/bin/sh

mount -t proc none /proc
mount -t vfat -o noatime /dev/hda1 /supercard
# some CF cards do not have a partition table
# try mounting /dev/hda if mounting /dev/hda1 fails
if [ "$?" != "0" ]
then
	mount -t vfat -o noatime /dev/hda /supercard
	[ "$?" = "0" ] || echo "Sorry, failed to mount your CF card."
fi

. /etc/rc.common
