.\" This man page originally written by pema@niksula.hut.fi
.TH xbill 1 "January 1997" "Version 2.0"
.de BP
.sp
.ti -.2i
\(**
..

.SH NAME
xbill -- save your computers from Wingdows [TM] virus
.SH SYNOPSIS
.hy 0
.na
.B xbill [-l|-L\fI starting level\fP] [-v]
.ad b
.hy 1
.SH DESCRIPTION
Ever get the feeling that nothing is going right?  You're a sysadmin, and
someone's trying to destroy your computers.  The little people running
around the screen are trying to infect your computers with Wingdows [TM],
a virus cleverly designed to resemble a popular operating system.  Your
objective is to click the mouse on them, ending their potential threat.
If one of the people reaches a computer, it will attempt to replace your
operating system with the virus it carries. It will then attempt to run off
the screen with your vital software.  The game ends when only 0 or 1 of
your computers is being productive.  Additionally, some computers are
connected with network cables.  When one computer on a network becomes 
infected, a spark will be sent down the cable, and will infect the computer
on the other end when it reaches there.
.PP
Clicking the button on one of the little people will cause it to cry out in
pain and melt (id software eat your heart out!), dropping the stolen os if it
is carrying one.  If a computer is running Wingdows or is temporarily off, the
os can be dragged back to the computer (or another computer compatible with
that os).  
To extinguish a spark drag the bucket of water from the upper left corner onto
it.
.PP
The status bar at the bottom tells the following:
.br
        Number of Bills on/off the screen
.br
        Number of Computers running their OS/off/Wingdows
.br
        Level
.br
        Score
.SH OPTIONS
.TP
.B \-l\fI n\fP, \-L\fI n
Start at level \fIn\fP.
.TP
.B \-v
Print version number and exit.
.TP
.B \-h
Print help and exit.
.TP
All standard X Intrinsics options are also supported.

.SH AUTHORS
Main Programmer:
.br
	Brian Wellington <bwelling@tis.com>
.br
Programming & graphics:
.br
	Matias Duarte <matias@hyperimage.com>
.br

.SH COPYING
Copyright (c) 1994-6 Psychosoft
.PP
It's FREE! If you want to express your undying gratitude to us for
bringing a small bit of meaning into your otherwise pointless
existence, you could always send us e-mail.
XBill is distributed under the GNU Public License.
.PP
Go play the game now!
