.TH CHVT 1 "07 Oct 1997" "Console tools" "Linux User's Manual"

.SH NAME
chvt \- change foreground virtual terminal

.SH SYNOPSIS
.BI chvt N

.SH DESCRIPTION
The command
.B chvt
.I N
makes
.RI /dev/tty N
the foreground terminal. The corresponding screen is created if it did not
exist yet. To get rid of unused VTs, use
.BR deallocvt (1).
.PP
The keymap action
.RI `Console_ N '
(usually bound to key combination 
.RI (Ctrl\-)LeftAlt\-F N ,
with 
.I N
in the range 1-12, and to 
.RI RightAlt\-F N\-12
with
.I N
in the range 13-24) also allows to switch to another VT, but really switches
only if it is already allocated. This prevents allocating new VTs with a
misplaced keystroke.

.SH "SEE ALSO"

.BR deallocvt (1).
