.TH DEALLOCVT 1 "06 Oct 1997" "Console tools" "Linux User's Manual"

.SH NAME
deallocvt \- deallocate unused virtual terminals

.SH SYNOPSIS
.BI "deallocvt [ " "N1 N2" " ... ]"

.SH DESCRIPTION

If given no argument, the program
.B deallocvt
deallocates kernel memory and data structures
for all unused virtual terminals.
If arguments
.I Ni
are given, only TTY's
.RI /dev/tty Ni
are deallocated.

A virtual terminal is unused if it is not the foreground console,
and no process has it open for reading or writing, and no text
has been selected on its screen.

.SH "SEE ALSO"
.BR chvt (1),
.BR openvt (1).
