#!/usr/bin/python

# Program to display factorials and test "fact.py".

import fact
import sys
import string

args = sys.argv[1:]
if (args == []):
	print "This program calculates factorials."
	print
	print "Usage:", sys.argv[0], "expression or numbers"
	sys.exit(1)
else:
	try:
		num = eval(string.join(args))
		print "fact(", num, ") =", fact.fact(num)
	except:
		for arg in args:
			num = eval(arg)
			print "fact(", num, ") =", fact.fact(num)
