.TH matho-primes 1

.SH NAME
matho-primes \- generate consecutive prime numbers

.SH SYNOPSIS
.B matho-primes
[start [stop]] ["twin"] ["pal" [base]]

.SH DESCRIPTION
This program quickly computes any number of consecutive prime numbers using a memory efficient
sieve algorithm and dumps them to standard output.
Generates up to 19 digit primes.
They are displayed one prime per line in ascending order.

A range may be
specified on the command line, otherwise the starting number and
the number of primes to output is prompted for.
The range is "start" to "stop", inclusive, and "stop" must
be greater than "start".

If "twin" is specified on the command line, only twin primes will be displayed.
Twin primes are two primes that differ in value by 2.
They are displayed together on the same line.

If "pal" is specified at the end of the command line, only palindromic primes are displayed.
The palindromic base may be specified, the default is base 10.

.SH SEE ALSO
mathomatic(1), matho-pascal(1)

.SH AUTHOR
George Gesslein II
