.TH matho-pascal 1

.SH NAME
matho-pascal \- display Pascal's triangle

.SH SYNOPSIS
.B matho-pascal
[number-of-lines]

.SH DESCRIPTION
This utility is part of the
.B mathomatic(1)
package and calculates up to 100 lines of Pascal's triangle,
dumping them to standard output.
The default is to center one screen full.

Every number inside Pascal's triangle is the sum of the two numbers
immediately above it.

Each line of Pascal's triangle is the same as binomial coefficients
for a given power.

The sum of all numbers in each line of Pascal's triangle is a power of 2.

.SH SEE ALSO
mathomatic(1), matho-primes(1), matho-sumsq(1)

.SH REPORTING BUGS
Report bugs to <gesslein@panix.com>.

.SH AUTHOR
George Gesslein II <gesslein@panix.com>
