.TH matho-pascal 1

.SH NAME
matho-pascal \- display Pascal's Triangle

.SH SYNOPSIS
.B matho-pascal
[number-of-lines]

.SH DESCRIPTION
This program calculates up to 100 lines of Pascal's Triangle
and dumps it to standard output.
The default is to center one screen full.

Every number inside Pascal's Triangle is the sum of the two numbers
immediately above it.
Pascal's Triangle is the same as binomial coefficients.

.SH SEE ALSO
mathomatic(1), matho-primes(1)

.SH AUTHOR
George Gesslein II
