#!/bin/sh

mount -t proc none /proc
mount -t vfat -o noatime /dev/dldi1 /media
# some CF cards do not have a partition table
# try mounting /dev/dldi if mounting /dev/dldi1 fails
if [ "$?" != "0" ]
then
	mount -t vfat -o noatime /dev/dldi /media
	[ "$?" = "0" ] || echo "Sorry, failed to mount DLDI device."
fi
mount -t ramfs none /var/run
mount -t ramfs none /tmp
. /etc/rc.common
