# apps/sysconfig/about/Makefile

TARGET_SO=clock.so
INSTALL_BINDIR=$(INSTALL_DIR)/bin/sysconfig

OBJS=nxclock.o nxsunclock.o scfxn.o astro.o hashdb_api.o hashdb_low.o

INCLUDES=-I../include

include $(BASE_DIR)/Rules.make

