#!/bin/sh

[ -e /etc/rc.defaults ] && . /etc/rc.defaults
[ -e /etc/rc.conf ] && . /etc/rc.conf

case "$1" in
	start)
		if [ -n "$essid" ]
		then
			echo "Configuring wireless interface:"
			echo "ESSID:    $essid"
			iwconfig nds essid $essid
			
			if [ -n "$channel" ]
			then 
				echo "Channel:  $channel"
				iwconfig nds channel $channel
			fi

			if [ -n "$wepkey" ]
			then
				echo "Setting wepkey."
				iwconfig nds key $wepkey
			fi
		else
			echo "Not configuring network:"
			echo "No ESSID defined. See /etc/rc.defaults!"
			exit 1
		fi

		# configure the interface
		ifconfig nds down
		if [ "$use_dhcp" = "YES" ]
		then
			echo "Configuring network via DHCP."
			# We have very little RAM, so don't fork a new
			# process for the dhcp client. This is the last
			# command to run anyway if using dhcp.
			exec udhcpc -n -q -i nds
			### NOT REACHED ###
		elif [ -n "$ip" ] && [ -n "$gateway" ]
		then
			echo "Configuring network:"
			echo "IP:        $ip"
			echo "Gateway:   $gateway"
			ifconfig nds $ip up
			route add default gw $gateway

			# Let users optionally configure netmask and broadcast.
			# Thanks to chatterbug89 for pointing out that this
			# was missing.
			if [ -n "$netmask" ]
				echo "Netmask:   $netmask"
				ifconfig nds netmask $netmask
			fi
			if [ -n "$broadcast" ]
				echo "Broadcast: $broadcast"
				ifconfig nds broadcast $broadcast
			fi
		else
			echo "Not configuring network:"
			echo "No static configuration found and DHCP is disabled."
			exit 1
		fi

		exit 0
	;;
	stop)
		echo "Stopping network."
		ifconfig nds down
		kill `pidof udhcpc` 2> /dev/null
	;;	
	restart)
		$0 stop
		$0 start
	;;
	*)
		echo "Usage: $0 <start|stop|restart>"
		exit 1
	;;
esac

