#!/bin/sh

[ -e /etc/rc.defaults ] && . /etc/rc.defaults
[ -e /etc/rc.conf ] && . /etc/rc.conf

case "$1" in
	start)
		if [ -n "$wfc_config" ]
		then
			eval `wfcdump -c $wfc_config`
			broadcast=
		fi

		if [ -n "$essid" ]
		then
			iwconfig_args=""

			echo "Configuring wireless interface:"
			echo "ESSID:    \"$essid\""
			iwconfig_args="$iwconfig_args essid \"$essid\""
			
			if [ -n "$channel" ]
			then 
				echo "Channel:  $channel"
				iwconfig_args="$iwconfig_args channel $channel"
			fi

			if [ -n "$wepkey" ]
			then
				echo "Setting wepkey."
				iwconfig_args="$iwconfig_args key \"$wepkey\""
			fi

			iwconfig nds $iwconfig_args
			sleep 1

		else
			echo "Not configuring network:"
			echo "No ESSID defined. See /etc/rc.defaults!"
			exit 1
		fi

		ifconfig nds down
		sleep 1

		if [ -z "$ip" ]
		then
			echo "Configuring network via DHCP."
			# We have very little RAM, so use 'exec' to avoid
			# forking a new process for the dhcp client. This is
			# the last command to run anyway if using dhcp.
			exec udhcpc -n -q -i nds
			### NOT REACHED ###
		elif [ -n "$gateway" ]
		then

			ifconfig_args=""
			route_args=""

			echo "Configuring network:"
			echo "IP:        $ip"
			echo "Gateway:   $gateway"
			ifconfig_args="$ifconfig_args $ip"

			if [ -n "$netmask" ]
			then
				echo "Netmask:   $netmask"
				ifconfig_args="$ifconfig_args netmask $netmask"
			fi

			if [ -n "$broadcast" ]
			then
				echo "Broadcast: $broadcast"
				ifconfig_args="$ifconfig_args broadcast $broadcast"
			fi

			ifconfig nds $ifconfig_args up
			sleep 1
			route add default gw $gateway

			if [ -n "$dns1" ]
			then
				echo "1st DNS:   $dns1"
				echo "nameserver $dns1" > /etc/resolv.conf
				if [ -n "$dns2" ]
				then
					echo "2nd DNS:   $dns2"
					echo "nameserver $dns2" >> /etc/resolv.conf
				fi
			fi
		else
			echo "Not configuring network:"
			echo "Static configuration incomplete and DHCP is disabled."
			exit 1
		fi

		exit 0
	;;
	stop)
		echo "Stopping network."
		ifconfig nds down
		kill `pidof udhcpc` 2> /dev/null
	;;	
	restart)
		$0 stop
		$0 start
	;;
	*)
		echo "Usage: $0 <start|stop|restart>"
		exit 1
	;;
esac

