.\" Hint for Emacs: -*- nroff -*-
.\" This is the manual page for retawq. To open it in a _human-readable_ form,
.\" try a command like "man retawq" or "man ./retawq.1".
.\"
.\" retawq/docu/retawq.1 - manual page
.\" This file is part of retawq, a network client created by Arne Thomassen;
.\" retawq is basically released under certain versions of the GNU General
.\" Public License and WITHOUT ANY WARRANTY.
.\" Read the file COPYING for license details, README for program information.
.\" Copyright (C) 2001-2005 Arne Thomassen <arne@arne-thomassen.de>
.TH retawq 1 "19 March 2005" "retawq 0.2.6b" "retawq manual"
.SH NAME
retawq \- a multi-threaded web browser for text terminals
.SH DESCRIPTION
retawq is an interactive, multi-threaded network client (web browser) for text terminals on computers with Unix-like operating systems. It is written in C, fast, small, nicely configurable, and comfortable; e.g. the low-level network communications are performed in a non-blocking way, and you can keep open as many "virtual windows" as you want and work simultaneously in two of them in a split-screen mode.
.P
The most recent version of retawq is available on the project home page <http://retawq.sourceforge.net/>.
.SH OPTIONS
retawq provides dozens of compile-time, command-line and run-time options, e.g. for internationalization/localization support and proxy configuration. Too many to explain them all here, but see also "see also"...
.SH LICENSE
retawq is basically released under certain versions of the GNU General Public License and WITHOUT ANY WARRANTY. Read the file
.I retawq/COPYING
(in the release package) for license details.
.SH BUGS
This program has no bugs. no bugs. no bugs. no *WHAP* thank you.
.\" Found in frotz(6) :-)
Seriously: this early release of retawq has several known problems. If you run into one of them, please try a more recent version - the program is continuously improved...
.SH AUTHOR
Arne Thomassen <arne@arne-thomassen.de>
.SH SEE ALSO
Extensive documentation about retawq is available in HTML form by way of the file
.I retawq/docu/index.html
in the release package.
