#!/bin/sh
sed -e "s/&Agrave;/À/g" | \
sed -e "s/&Aacute;/Á/g" | \
sed -e "s/&Acirc;/Â/g" | \
sed -e "s/&Atilde;/Ã/g" | \
sed -e "s/&Auml;/Ä/g" | \
sed -e "s/&Aring;/Å/g" | \
sed -e "s/&AElig;/Æ/g" | \
sed -e "s/&Ccedil;/Ç/g" | \
sed -e "s/&Egrave;/È/g" | \
sed -e "s/&Eacute;/É/g" | \
sed -e "s/&Ecirc;/Ê/g" | \
sed -e "s/&Euml;/Ë/g" | \
sed -e "s/&Igrave;/Ì/g" | \
sed -e "s/&Iacute;/Í/g" | \
sed -e "s/&Icirc;/Î/g" | \
sed -e "s/&Iuml;/Ï/g" | \
sed -e "s/&ETH;/Ð/g" | \
sed -e "s/&Ntilde;/Ñ/g" | \
sed -e "s/&Ograve;/Ò/g" | \
sed -e "s/&Oacute;/Ó/g" | \
sed -e "s/&Ocirc;/Ô/g" | \
sed -e "s/&Otilde;/Õ/g" | \
sed -e "s/&Ouml;/Ö/g" | \
sed -e "s/&times;/×/g" | \
sed -e "s/&Oslash;/Ø/g" | \
sed -e "s/&Ugrave;/Ù/g" | \
sed -e "s/&Uacute;/Ú/g" | \
sed -e "s/&Ucirc;/Û/g" | \
sed -e "s/&Uuml;/Ü/g" | \
sed -e "s/&Yacute;/Ý/g" | \
sed -e "s/&THORN;/Þ/g" | \
sed -e "s/&szlig;/ß/g" | \
sed -e "s/&agrave;/à/g" | \
sed -e "s/&aacute;/á/g" | \
sed -e "s/&acirc;/â/g" | \
sed -e "s/&oacute;/ã/g" | \
sed -e "s/&auml;/ä/g" | \
sed -e "s/&aring;/å/g" | \
sed -e "s/&aelig;/æ/g" | \
sed -e "s/&ccedil;/ç/g" | \
sed -e "s/&egrave;/è/g" | \
sed -e "s/&eacute;/é/g" | \
sed -e "s/&ecirc;/ê/g" | \
sed -e "s/&euml;/ë/g" | \
sed -e "s/&igrave;/ì/g" | \
sed -e "s/&iacute;/í/g" | \
sed -e "s/&icirc;/î/g" | \
sed -e "s/&iuml;/ï/g" | \
sed -e "s/&eth;/ð/g" | \
sed -e "s/&ntilde;/ñ/g" | \
sed -e "s/&ograve;/ò/g" | \
sed -e "s/&oacute;/ó/g" | \
sed -e "s/&ocirc;/ô/g" | \
sed -e "s/&otilde;/õ/g" | \
sed -e "s/&ouml;/ö/g" | \
sed -e "s/&divide;/÷/g" | \
sed -e "s/&oslash;/ø/g" | \
sed -e "s/&ugrave;/ù/g" | \
sed -e "s/&uacute;/ú/g" | \
sed -e "s/&ucirc;/û/g" | \
sed -e "s/&uuml;/ü/g" | \
sed -e "s/&yacute;/ý/g" | \
sed -e "s/&thorn;/þ/g" | \
sed -e "s/&yuml;/ÿ/g"
