.TH MATHOMATIC 1

.SH NAME
mathomatic \- automatic algebraic manipulator

.SH SYNOPSIS
.B mathomatic
[
.B -chqtuv
] [
.B -m
number
] [
input_files
]

.SH DESCRIPTION
Mathomatic is a portable, general purpose CAS (Computer Algebra
System) that can automatically solve, simplify,
combine, and compare algebraic equations.
It does some calculus and handles all algebra, except trigonometry and logarithms.
It is entirely hand-written in optimized C.
It does not permit extremely large expressions, which can take a lot
of memory and time.
Instead reliability, ease of use, and speed are its features.

.SH OPTIONS
.TP
.B \-c
Toggle color mode.
This mode outputs ANSI escape sequences to make each level of
parentheses a different color, for easier reading.

.TP
.B \-h
Enable HTML mode (also valid XHTML).
This makes Mathomatic output suitable for inclusion in a web page.
The color mode flag affects this mode, allowing HTML color output.
It is recommended that the web page have a black background in color mode.

.TP
.B \-m number
Change the memory size of equation spaces.
It is followed by a floating point number which is a multiplier
of the default equation size.
Please don't set this higher than 10, unless you know what you are doing.

.TP
.B \-q
Sets quiet mode.
Prompts are not displayed.

.TP
.B \-t
Sets test mode.
Used when testing and comparing output.
Bypasses loading startup file, turns off color mode, etc.

.TP
.B \-u
Guarantee standard output is unbuffered.

.TP
.B \-v
Display version number and compile flags used and exit.

.SH GENERAL
First you type in your algebraic equations in standard infix notation,
then you can solve them by just typing in the variable, or
perform operations on them with simple English commands.
Type "help" for the help command.
If the command is longer than 4 letters, you only need
to type in the first 4 letters.
Most commands operate on the current equation by default.

Documentation is available in HTML format,
see the web site "www.mathomatic.org".

.SH ENVIRONMENT
.TP
.B EDITOR
Editor to use for the edit command.

.SH FILES
.TP
.B ~/.mathomaticrc
Optional startup file containing Mathomatic set options.
It should be a text file with one set option per line.
Do not include the word "set".

.SH AUTHOR
George Gesslein II
