/* Automatically generated by po2tbl.sed from console-tools.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"\
Usage: %s psffont_in sfm_file [psffont_out]\n\
Add a Unicode character table to a PSF font\n", 2},
  {"input psffont filename", 3},
  {"screen-font-map filename", 4},
  {"output psffont filename", 5},
  {"%s: wrong number of arguments\n", 6},
  {"%s: psffont and chartable cannot both be stdin\n", 7},
  {"Loading unicode map from %s.\n", 8},
  {"\
Usage: %s psffont chartable [outfile]\n\
Extract a Unicode character table from a PSF font\n", 9},
  {"psffont filename", 10},
  {"output filename", 11},
  {"%s: Font has no character table\n", 12},
  {"\
Usage: %s [options] psffont [outfile]\n\
Strip Unicode character table from a PSF font\n", 13},
  {"%s: Font already had no character table\n", 14},
  {"?UNKNOWN?", 15},
  {"kb mode was %s\n", 16},
  {"[ if you are trying this under X, it might not work\n", 17},
  {"since the X server is also reading /dev/console ]\n", 18},
  {"caught signal %d, cleaning up...\n", 19},
  {"usage: %s [options...] <command>\n", 20},
  {"display only the raw scan-codes.", 21},
  {"display only the interpreted keycodes (default).", 22},
  {"display only keymap-translated chars.", 23},
  {"display unicode-translated chars.", 24},
  {"set the timeout to N seconds.", 25},
  {"timeout value must be numeric", 26},
  {"no non-option arguments allowed", 27},
  {"WARNING: Unicode mode is experimental -- output may be wrong\n", 28},
  {"press any key (program terminates after %us of last keypress)...\n", 29},
  {"keycode %3d %s\n", 30},
  {"release", 31},
  {"press", 32},
  {"\
\n\
Usage:\n\
\t%1$s [ metabit | meta | bit | escprefix | esc | prefix ]\n\
Each vt has his own copy of this bit. Use\n\
\t%1$s [arg] < /dev/ttyn\n\
to change the settings of another vt.\n\
The setting before and after the change are reported.\n", 33},
  {"Meta key sets high order bit\n", 34},
  {"Meta key gives Esc prefix\n", 35},
  {"Strange mode for Meta key?\n", 36},
  {"Error reading current setting. Maybe stdin is not a VT?\n", 37},
  {"unrecognized argument", 38},
  {"old state:    ", 39},
  {"new state:    ", 40},
  {"\
Usage: %s [option]\n\
Report and set keyboard mode\n", 41},
  {"print this help information and exit", 42},
  {"report version and exit", 43},
  {"ASCII or 8bit mode (XLATE)", 44},
  {"keycode mode (MEDIUMRAW)", 45},
  {"UTF-8 mode (UNICODE)", 46},
  {"scancode mode (RAW)", 47},
  {"set mode", 48},
  {"%s: unknown mode: %s\n", 49},
  {": error reading keyboard mode\n", 50},
  {"The keyboard is in raw (scancode) mode\n", 51},
  {"The keyboard is in mediumraw (keycode) mode\n", 52},
  {"The keyboard is in the default (ASCII) mode\n", 53},
  {"The keyboard is in Unicode (UTF-8) mode\n", 54},
  {"The keyboard is in some unknown mode\n", 55},
  {": error setting keyboard mode\n", 56},
  {"too many keydefinitions on one line", 57},
  {"Usage: %s [option...] [mapfile...]\n", 58},
  {"clear kernel compose table", 59},
  {"load default keymap file", 60},
  {"output a \"defkeymap.c\" to stdout", 61},
  {"clear kernel string table", 62},
  {"be silent", 63},
  {"report the changes", 64},
  {"report more changes", 65},
  {"syntax error in map file\n", 66},
  {"key bindings not changed\n", 67},
  {"Cannot find %s\n", 68},
  {"cannot open file %s\n", 69},
  {"addmap called with bad index %d", 70},
  {"adding map %d violates explicit keymaps line)", 71},
  {"killkey called with bad index %d", 72},
  {"killkey called with bad table %d", 73},
  {"addkey called with bad index %d", 74},
  {"addkey called with bad table %d", 75},
  {"%s: addfunc called with bad func %d\n", 76},
  {"%s: addfunc: func_buf overflow\n", 77},
  {"compose table overflow\n", 78},
  {"Warning: Compose char %4x ('%c','%c') > 0xFF will be truncated to %2x\n", 79},
  {"  (Linux kernel < 2.3.X can't handle unicode compose chars properly)\n", 80},
  {"Keymap %d: Permission denied\n", 81},
  {"keycode %d, table %d = %d%s\n", 82},
  {"    FAILED", 83},
  {"failed to bind key %d to value %d\n", 84},
  {"deallocate keymap %d\n", 85},
  {"%s: could not deallocate keymap %d\n", 86},
  {"%s: cannot deallocate or clear keymap\n", 87},
  {"%s: failed to restore keyboard mode\n", 88},
  {"\
%s: warning: this map uses Unicode symbols\n\
    (perhaps you want to do `kbd_mode -u'?)\n", 89},
  {"failed to bind string '%s' to function %s\n", 90},
  {"failed to clear string %s\n", 91},
  {"too many compose definitions\n", 92},
  {"KDSKBDIACR failed\n", 93},
  {"impossible error in do_constant", 94},
  {"\
\n\
Changed %d key%s and %d string%s.\n", 95},
  {"Loaded %d compose definition%s.\n", 96},
  {"(No change in compose definitions.)\n", 97},
  {"loadkeys: don't know how to compose for %s\n", 98},
  {"\
Usage: %s\n\
Print kernel scancode-to-keycode mapping table\n", 99},
  {"Plain scancodes xx (hex) versus keycodes (dec)\n", 100},
  {"0 is an error; for 1-88 (0x01-0x58) scancode equals keycode\n", 101},
  {"\
\n\
\n\
Escaped scancodes e0 xx (hex)\n", 102},
  {"failed to get keycode for scancode 0x%x\n", 103},
  {"KDGKBENT at index 0 in table %d: ", 104},
  {"%s: cannot find any keymaps?\n", 105},
  {"%s: plain map not allocated? very strange ...\n", 106},
  {"KDGKBENT at index %d in table %d: ", 107},
  {"KDGKBDIACR failed\n", 108},
  {"keycode range supported by kernel:           1 - %d\n", 109},
  {"max number of actions bindable to a key:         %d\n", 110},
  {"number of keymaps in actual use:                 %d\n", 111},
  {"of which %d dynamically allocated\n", 112},
  {"ranges of action codes supported by kernel:\n", 113},
  {"number of function keys supported by kernel: %d\n", 114},
  {"max nr of compose definitions: %d\n", 115},
  {"nr of compose definitions in actual use: %d\n", 116},
  {"\
Symbols recognized by %s:\n\
(numeric value, symbol)\n\
\n", 117},
  {"\
\n\
The following synonyms are recognized:\n\
\n", 118},
  {"\
\n\
Recognized modifier names and their column numbers:\n", 119},
  {"impossible: not meta?\n", 120},
  {"KDGKBSENT at index %d: ", 121},
  {"Usage: %s [options...]\n", 122},
  {"display information about keyboard driver", 123},
  {"display above and symbols known to loadkeys", 124},
  {"display keytable in hexadecimal notation", 125},
  {"don't use short-hand notations, one row per keycode", 126},
  {"one line per (modifier,keycode) pair", 127},
  {"display only the function key strings", 128},
  {"display only key bindings", 129},
  {"choose output shape, where <shape> is:", 130},
  {" 0 = default", 131},
  {" 1 = same as --full-table", 132},
  {" 2 = same as --separate-lines", 133},
  {" 3 = one line per keycode, until 1st hole", 134},
  {"display only compose key combinations", 135},
  {"interpret character action codes to be from the", 136},
  {"specified character set", 137},
  {"display this help text and exit", 138},
  {"display version information and exit", 139},
  {"\
\n\
available charsets:\n", 140},
  {"\
Usage:\t%1$s [-v] [-L] [-D] [-F] [[+|-][ num | caps | scroll ]]\n\
Thus,\n\
\t%1$s +caps -num\n\
will set CapsLock, clear NumLock and leave ScrollLock unchanged.\n\
The settings before and after the change (if any) are reported\n\
when the -v option is given or when no change is requested.\n\
Normally, %1$s influences the vt flag settings\n\
(and these are usually reflected in the leds).\n\
With -L, %1$s only sets the leds, and leaves the flags alone.\n\
With -D, %1$s sets both the flags and the default flags, so\n\
that a subsequent reset will not change the flags.\n", 141},
  {"%s: unknown argument: %s\n", 142},
  {"NumLock %s   CapsLock %s   ScrollLock %s\n", 143},
  {"Error reading current led setting. Maybe stdin is not a VT?\n", 144},
  {"Error reading current flags setting. Maybe an old kernel?\n", 145},
  {"Error resetting ledmode\n", 146},
  {"Current default flags:  ", 147},
  {"Current flags:          ", 148},
  {"Current leds:           ", 149},
  {"Old default flags:    ", 150},
  {"New default flags:    ", 151},
  {"Old flags:            ", 152},
  {"New flags:            ", 153},
  {"Old leds:             ", 154},
  {"New leds:             ", 155},
  {"loadunimap: out of memory\n", 156},
  {"Out of Memory\n", 157},
  {"Out of Memory?\n", 158},
  {"Warning: line too long in unicode map.\n", 159},
  {"Bad input line: %s\n", 160},
  {"unicode map: glyph number (0x%x) larger than font length\n", 161},
  {"unicode map: bad end of range (0x%x)\n", 162},
  {"\
unicode map: Corresponding to a range of font positions, there should be a \
Unicode range\n", 163},
  {"\
unicode map: Bad Unicode range corresponding to font position range \
0x%x-0x%x\n", 164},
  {"\
unicode map: Unicode range U+%x-U+%x not of the same length as font position \
range 0x%x-0x%x\n", 165},
  {"unicode map: trailing junk (%s) ignored\n", 166},
  {"Would save %d SFM entries in `%s'.\n", 167},
  {"Couldnt get a file descriptor referring to the console\n", 168},
  {"Unknown PSF mode number (%d).\n", 169},
  {"Error: unknown charset `%s'.\n", 170},
  {"assuming iso-8859-2 %s\n", 171},
  {"assuming iso-8859-3 %s\n", 172},
  {"assuming iso-8859-4 %s\n", 173},
  {"unknown keysym `%s'\n", 174},
  {"%s: %s child exited anormally with code %d.\n", 175},
  {"%s: %s child was terminated by signal %d.\n", 176},
  {"%s: %s child was stopped by signal %d.\n", 177},
  {"Feeder", 178},
  {"Decompressor", 179},
  {"Identifier", 180},
  {"chld_handler()", 181},
  {"%s child exited OK.\n", 182},
  {"fread magic", 183},
  {"decompressor fork", 184},
  {"decompressor: close file[1]", 185},
  {"decompressor: close uncompressed[0]", 186},
  {"decompressor: dup2 file[0]", 187},
  {"decompressor: dup2 uncompressed[1]", 188},
  {"Decompressor program not found: %s\n", 189},
  {"decompressor: execlp", 190},
  {"feeder fork", 191},
  {"feeder: close uncompressed[0]", 192},
  {"feeder: write zmagicbuf", 193},
  {"feeder: feed", 194},
  {"fread", 195},
  {"identifier fork", 196},
  {"identifier: close identified[0]", 197},
  {"identifier: write magicIDbuf", 198},
  {"identifier: feed", 199},
  {"Zombie %d caught.\n", 200},
  {"One for nothing.\n", 201},
  {"Warning: ignoring a possible path (too long).", 202},
  {"feeder", 203},
  {"decompressor", 204},
  {"identifier", 205},
  {"findfile(): timeout waiting for undead child(ren) ?\n", 206},
  {"Buffer overflow - aborting\n", 207},
  {"Cannot stat map file", 208},
  {"16bit screen-map MUST be a regular file.\n", 209},
  {"fseek failed reading binary 16bit screen-map", 210},
  {"Cannot read [new] map from file", 211},
  {"Input screen-map is binary.\n", 212},
  {"PIO_UNISCRNMAP ioctl", 213},
  {"Assuming 8bit screen-map - MUST be a regular file.\n", 214},
  {"fseek failed assuming 8bit screen-map", 215},
  {"fseek() returned ESPIPE !\n", 216},
  {"fseek for binary 8bit screen-map", 217},
  {"Cannot read [old] map from file", 218},
  {"PIO_SCRNMAP ioctl", 219},
  {"Error parsing symbolic map\n", 220},
  {"uni_screen_map_read_ascii() can't read line", 221},
  {"GIO_UNISCRNMAP ioctl error", 222},
  {"GIO_SCRNMAP ioctl error", 223},
  {"Error writing map to file", 224},
  {"%s: Unexpected arguments.\n", 225},
  {"Usage:  %s [options] [commands]\n", 226},
  {"List operations as they are done", 227},
  {"Do not change the console state nor write to any file", 228},
  {"\
(N in 0..32) Choose the right font from a codepage that\n\
contains three fonts (only 8/14/16 allowed then), or choose\n\
default font, ie. \"default8xN\"", 229},
  {"Suppress loading of a screen-font map [use with care]", 230},
  {"When loading an ACM, activate G1 charset instead of G0", 231},
  {"Use `device' as console device for ioctls", 232},
  {"Load the console-font from specified file", 233},
  {"Load a default font from a file", 234},
  {"Restore ROM font (does not work with all kernels)", 235},
  {"\
Load the SFM from specified file\n\
(instead of the one in font-file, if any)", 236},
  {"Merge SFM fallbacks from file into SFM", 237},
  {"Load the ACM from specified file", 238},
  {"Write current font to prefered format (now: psf-with-sfm)", 239},
  {"Write current font to PSF file before loading a new one", 240},
  {"Same as -old-font-psf, and add current SFM in the PSF file", 241},
  {"Write current font to RAW file before loading a new one", 242},
  {"Write current ACM to file before loading a new one", 243},
  {"Write current SFM to file before loading a new one", 244},
  {"too many `-' as filenames", 245},
  {"--char-height argument should be in 1..31", 246},
  {"only one font file is allowed", 247},
  {"only one ACM is allowed", 248},
  {"only one SFM is allowed", 249},
  {"multiple requests for SFM handling", 250},
  {"WARNING: not using a unimap may lead to erroneous display !\n", 251},
  {"realloc fallback_files", 252},
  {"only one output RAW font-file is allowed", 253},
  {"only one output PSF font-file is allowed", 254},
  {"only one output PSF+SFM font-file is allowed", 255},
  {"only one output ACM file is allowed", 256},
  {"only one output SFM file is allowed", 257},
  {"unknown option", 258},
  {"no non-option arguments are valid", 259},
  {"nothing to do", 260},
  {"Saving raw old font", 261},
  {"Saving PSF old font", 262},
  {"Saving PSF+unimap old font", 263},
  {"Would save ACM to file `%s'.\n", 264},
  {"Saving ACM to file `%s'.\n", 265},
  {"Would load ACM from `%s'\n", 266},
  {"Loading ACM from `%s'\n", 267},
  {"Error reading ACM file.\n", 268},
  {"Would read screen-font map from %s.\n", 269},
  {"Reading screen-font map from %s.\n", 270},
  {"Requesting SFM from kernel.\n", 271},
  {"No valid SFM currently loaded. Aborting.\n", 272},
  {"Reading SFM fallbacks from `%s'.\n", 273},
  {"Read %u fallback entries.\n", 274},
  {"WARNING: No SFM found in file or kernel ?  Ignoring fallback file.\n", 275},
  {"Would set kernel SFM.\n", 276},
  {"Setting kernel SFM.\n", 277},
  {"Cannot find a default font file.\n", 278},
  {"Cannot find default font file `default8x%02d'.\n", 279},
  {"Cannot open font file `%s'.\n", 280},
  {"Only fontsize 256 supported.\n", 281},
  {"Would load %d-chars %dx%d font from file `%s'.\n", 282},
  {"Loading %d-chars %dx%d font from file `%s'.\n", 283},
  {"Reading default SFM from `%s'.\n", 284},
  {"Cannot write SFM into non-PSF font-file.\n", 285},
  {"Can only save 8bit-wide fonts for now, and font is %d-bit wide.\n", 286},
  {"Can only save 256-chars fonts in RAW files, and font has %d chars.\n", 287},
  {"Found nothing to save.\n", 288},
  {"Would have saved 8x%d %s font file on `%s'%s.\n", 289},
  {"Saved 8x%d %s font file on `%s'%s.\n", 290},
  {", with SFM", 291},
  {", without SFM", 292},
  {"\
Usage: %s\n\
Displays a screen-font's contents.\n", 293},
  {"\
Usage: %s\n\
Clears the Unicode map from the console.\n\
Note: nowadays this kills kernel console output!\n", 294},
  {"\
Usage: %s [console]\n\
Dump the contents of the screen to stdout\n", 295},
  {"dump contents of screen s", 296},
  {"%s: Wrong number of args\n", 297},
  {"Out of memory\n", 298},
  {"Error reading %s\n", 299},
  {"Could not use /dev/vcs*, trying TIOCLINUX\n", 300},
  {"Out of memory.\n", 301},
  {"couldn't read %s, and cannot ioctl dump\n", 302},
  {"Strange ... screen is both %dx%d and %dx%d ??\n", 303},
  {"Out of memory?\n", 304},
  {"Error writing screen dump\n", 305},
  {"\
Usage: %s ON|on|off\n\
\n\
Set VESA blanking on console.\n", 306},
  {"turn blanking on", 307},
  {"%s: argument '%s' should be 'ON', 'on' or 'off'\n", 308},
  {"Usage: %s [option]\n", 309},
  {"don't print result", 310},
  {"Single-byte char mode.\n", 311},
  {"\
Usage:  %s COLSxROWS\n\
        %s COLS ROWS\n\
        %s -lines ROWS, with ROWS one of 25, 28, 30, 34, 36, 40, 44, 50, 60\n", 312},
  {"%s: Invalid number of columns: %s\n", 313},
  {"%s: Invalid number of rows: %s\n", 314},
  {"%s: Invalid arguments", 315},
  {"%s: Unrecognized argument", 316},
  {"%s: bad number of arguments\n", 317},
  {"%s: cannot find videomode file %s\n", 318},
  {"Invalid number of lines\n", 319},
  {"Old mode: %dx%d  New mode: %dx%d\n", 320},
  {"Old #scanlines: %d  New #scanlines: %d  Character height: %d\n", 321},
  {"%s: the command `%s' failed\n", 322},
  {"%s: don't forget to change TERM (maybe to con%dx%d or linux-%dx%d)\n", 323},
  {"Also the variables LINES and COLUMNS may need adjusting.\n", 324},
  {"%s: cannot get I/O permissions.\n", 325},
  {"\
Usage: %s [N1 N2 ...]\n\
Deallocate virtual terminal(s)\n", 326},
  {"virtual terminal", 327},
  {"%s: 0: illegal VT number\n", 328},
  {"%s: VT 1 is the console and cannot be deallocated\n", 329},
  {"%s: could not deallocate console %d\n", 330},
  {"%s: deallocating all unused consoles failed\n", 331},
  {"\
Usage: %s [vt_number]\n\
Print foreground console\n", 332},
  {"\
Usage: %s [vt_number]\n\
Change virtual terminal\n", 333},
  {"\
Usage: %s\n\
Show time in upper right hand corner of the console screen\n", 334},
  {"\
Usage: %s tty text\n\
Put text into the input buffer of a virtual terminal.\n", 335},
  {"device name", 336},
  {"text to insert", 337},
  {"%s: No tty specified.\n", 338},
  {"%s: No text specified.\n", 339},
  {"%s: too many arguments\n", 340},
  {"%s: could not open tty\n", 341},
  {"%s: TIOCSTI ioctl failed\n", 342},
};

int _msg_tbl_length = 342;
