#!/bin/sh

[ -e /etc/rc.defaults ] && . /etc/rc.defaults
[ -e /etc/rc.conf ] && . /etc/rc.conf

getip | read IP

DAEMON=esd
OPTIONS="-b -r 22050 -bind $IP -tcp -promiscuous"
case "$1" in
	start)
		echo "Starting $DAEMON"
		$DAEMON $OPTIONS &
	;;
	stop)
		echo "Stopping $DAEMON"
		kill -9 `pidof $DAEMON`
	;;	
	restart)
		$0 stop
		$0 start
	;;
	*)
		echo "Usage: $0 <start|stop|restart>"
		exit 1
	;;
esac

