#!/bin/sh

[ -e /etc/rc.defaults ] && . /etc/rc.defaults
[ -e /etc/rc.conf ] && . /etc/rc.conf

DAEMON=inetd
INETD_CONF=/etc/inetd.conf
SSH_HOST_KEY=/etc/dropbear_rsa_host_key

case "$1" in
	start)
		echo "Starting $DAEMON"
		
		# Check for existence of config file
		if [ ! -f $INETD_CONF ]
		then
			echo "$INETD_CONF not found!"
			echo "Please read /etc/inetd.conf.example"
			exit 1
		fi

		# Check for existence of dropbear key
		# Generate if not found and sshd enabled

		if grep ssh $INETD_CONF | grep -v "^#" >/dev/null \
			&& [ ! -e $SSH_HOST_KEY ]
		then
			echo "You have enabled dropbear in $INETD_CONF"
			echo "but there is no SSH host key yet."
			/usr/bin/dropbearkey -t rsa -f $SSH_HOST_KEY
		fi		
		
		# Check for existence of samba password
		# Generate if not found and smbd enabled

		if grep netbios-ssn $INETD_CONF | grep -v "^#" >/dev/null \
			&& [ ! -e /etc/smbpasswd ]
		then
			echo "Generating default smbpasswd"
			echo "You are advised to change this with smbpasswd"
			(echo uClinux ; echo uClinux) | /usr/bin/smbpasswd -a root -s
		fi
		$DAEMON &
	;;
	stop)
		echo "Stopping $DAEMON"
		kill -9 `pidof $DAEMON`
	;;	
	restart)
		$0 stop
		$0 start
	;;
	*)
		echo "Usage: $0 <start|stop|restart>"
		exit 1
	;;
esac

