#!/bin/sh

[ -e /etc/rc.defaults ] && . /etc/rc.defaults
[ -e /etc/rc.conf ] && . /etc/rc.conf

case "$1" in
	start)
		if [ -n "$essid" ] && [ -n "$channel" ]
		then
			echo "Configuring wireless interface:"
			echo "ESSID:    $essid"
			echo "Channel:  $channel"
			iwconfig nds essid $essid channel $channel
			if [ -n "$wepkey" ]
			then
				echo "Setting wepkey."
				iwconfig nds key $webkey
			fi
		else
			echo "Not configuring network:"
			echo "No ESSID or channel defined. See /etc/rc.defaults!"
			exit 1
		fi

		# configure the interface
		ifconfig nds down
		if [ "$use_dhcp" = "YES" ]
		then
			echo "Configuring network via DHCP."
			# XXX: other args are needed here?
			udhcpc -i nds
		elif [ -n "$ip" ] && [ -n "$gateway" ]
		then
			echo "Configuring network:"
			echo "IP:       $ip"
			echo "Gateway:  $gateway"
			ifconfig nds $ip up
			route add default gw $gateway
		else
			echo "Not configuring network:"
			echo "No static configuration found and DHCP is disabled."
			exit 1
		fi

		exit 0
	;;
	stop)
		echo "Stopping network."
		ifconfig nds down
	;;	
	restart)
		$0 stop
		$0 start
	;;
	*)
		echo "Usage: $0 <start|stop|restart>"
		exit 1
	;;
esac

