#!/bin/sh

[ -e /etc/rc.defaults ] && . /etc/rc.defaults
[ -e /etc/rc.conf ] && . /etc/rc.conf

DAEMON=syslogd

case "$1" in
	start)
		echo "Starting $DAEMON"
		$DAEMON &
	;;
	stop)
		echo "Stopping $DAEMON"
		kill -9 `pidof $DAEMON`
	;;	
	restart)
		$0 stop
		$0 start
	;;
	*)
		echo "Usage: $0 <start|stop|restart>"
		exit 1
	;;
esac

