.TH KBD\-COMPAT 8 "27 Oct 1997" "Console tools" "Linux User's Manual"

.SH NAME
kbd\-compat \- kbd\-compatibility wrapper scripts for Linux Console Tools.

.SH SYNOPSIS
.BI "setfont [ " "\-o font.orig" "] [" "\-H" "] [" "font.new" ]
.BI [ "\-m acm" "] [" "\-om acm.orig" ]
.BI [ "\-u sfm" "] [" "\-ou sfm.orig" ]
.BI [ \-v "] [" \-V ]
.br
.BI "loadunimap " sfm
.br
.BI "saveunimap " sfm.orig
.br
.BI "mapscrn [ " acm " ] [ " "\-o acm.orig" ]

.SH DESCRIPTION

All of these scripts are intended solely for backward compatibility with the
old `kbd' package, and are only needed by a few programs which rely on the
command\-line interface of these programs.  They are all implemented as
wrappers around the
.BR consolechars (8)
command.

These scripts may not be installed on your system. They will even hopefully
one day never be installed on any system again.

.SH SEE ALSO
.BR consolechars (8).
