.TH MATHOMATIC 1

.SH NAME
mathomatic \- automatic algebraic manipulator

.SH SYNOPSIS
.B mathomatic
[
.B -chqrtuv
] [
.B -m
number
] [
input_files
]

.SH DESCRIPTION
Mathomatic is a portable, general purpose CAS (Computer Algebra System)
that can symbolically solve, simplify, combine, and compare algebraic equations,
perform complex number and polynomial arithmetic, etc.
It does some calculus and handles all algebra, except trigonometry and logarithms.

Mathomatic is entirely hand-written in optimized C.
It does not permit extremely large expressions, which can take a lot
of memory and time.
Instead reliability, ease of use, and speed are its features.

All arithmetic is double precision floating point
with 14 decimal digits accuracy.

.SH OPTIONS
.TP
.B \-c
Toggle color mode.
This mode outputs ANSI escape sequences to make each level of
parentheses a different color, for easier reading.

.TP
.B \-h
Enable HTML output mode (also valid XHTML) and disable readline input.
This makes Mathomatic output suitable for inclusion in a web page.
The color mode flag affects this mode, allowing HTML color output.
By default, Mathomatic uses maximum brightness colors for HTML,
so it is recommended that the web page have a dark background.

.TP
.B \-m number
Change the memory size of equation spaces.
It is followed by a decimal floating point number which is a multiplier
of the default equation size.
Please don't set this higher than 10, unless you know what you are doing.

.TP
.B \-q
Set quiet mode.
The startup message and prompts are not displayed.
This is useful when piping or redirecting input into Mathomatic,
because the input won't be displayed,
so prompt output should be turned off.

.TP
.B \-r
Completely disable readline input processing.
Readline allows using the cursor keys and outputs terminal control codes
which can be turned off with this option.

.TP
.B \-t
Set test mode.
Used when testing and comparing output.
Bypasses loading startup file, turns off color mode and readline,
sets infinite screen width and height, etc.

.TP
.B \-u
Guarantee standard output is unbuffered.

.TP
.B \-v
Display version number, compile flags used, maximum memory usage, and then exit.
The maximum memory usage displayed does not include stack size (which varies) or executable size.

.SH GENERAL
First you type in your algebraic equations in standard infix notation,
then you can solve them by typing in the variable name at the prompt, or
perform operations on them with simple English commands.
Type "help" for the help command.
If the command is longer than 4 letters, you only need
to type in the first 4 letters.
Most commands operate on the current equation by default.

Documentation is available in HTML format,
see the documentation directory or the web site "www.mathomatic.org".

.SH ENVIRONMENT
.TP
.B EDITOR
This environment variable specifies the editor to use for the edit command.

.SH FILES
.TP
.B ~/.mathomaticrc
Optional startup file containing Mathomatic set options.
It should be a text file with one set option per line.
Do not include the word "set".

.SH REPORTING BUGS
Report bugs to <gesslein@panix.com>.

.SH AUTHOR
George Gesslein II <gesslein@panix.com>
