#!/bin/sh

mount -t proc none /proc
mount -t vfat -o noatime /dev/dldi1 /media
# some CF cards do not have a partition table
# try mounting /dev/dldi if mounting /dev/dldi1 fails
if [ "$?" != "0" ]
then
	mount -t vfat -o noatime /dev/dldi /media
	[ "$?" = "0" ] || echo "Sorry, failed to mount DLDI device."
fi
mount -t ramfs none /var/run
mount -t ramfs none /tmp
mount -t sysfs none /sys

# Create r/w /dev entries so dropbear will work
mknod /var/run/ttyp0 c 3 0
mknod /var/run/ttyp1 c 3 1
mknod /var/run/ttyp2 c 3 2
mknod /var/run/ttyp3 c 3 3
mknod /var/run/ttyp4 c 3 4
mknod /var/run/ttyp5 c 3 5
mknod /var/run/ttyp6 c 3 6
mknod /var/run/ttyp7 c 3 7
mknod /var/run/ttyp8 c 3 8
mknod /var/run/ttyp9 c 3 9
mknod /var/run/ttypa c 3 10
mknod /var/run/ttypb c 3 11
mknod /var/run/ttypc c 3 12
mknod /var/run/ttypd c 3 13
mknod /var/run/ttype c 3 14
mknod /var/run/ttypf c 3 15
. /etc/rc.common
