#!/bin/sh
# $Id$
: ${DIALOG=dialog}

./killall listing
./listing >listing.out &

$DIALOG --title "TAIL BOX" \
        --tailbox listing.out 24 70

case $? in
  0)
    echo "OK";;
  255)
    echo "ESC pressed.";;
esac

./killall listing
