.TH SL 6 "Jan 18, 2001"
.UC 5
.SH NAME
sl \- display animations aimed to correct users who accidentally enter
.B sl
instead of 
.BR ls .
.SH SYNOPSIS
.B sl
[
.B \-alFe
]
.SH DESCRIPTION
.B sl 
Displays animations aimed to correct users who accidentally enter 
.B sl 
instead of 
.BR ls . 
.SH OPTIONS
.TP
.B \-a
An accident seems to happen. You'll feel pity for people who cry for help.
.TP
.B \-l
shows little one.
.TP
.B \-F
It flies.
.TP
.B \-e
Allow interrupt by Ctrl+C.
.PP
.SH "SEE ALSO"
.BR ls (1)
.SH BUGS
It rarely shows contents of current directory.
.SH AUTHOR
.B sl
was written by Toyoda Masashi <toyoda@is.titech.ac.jp>. This manual page was
written by Brian Ristuccia
<brianr@debian.org> and Kenshi Muto <kmuto@debian.org> for the Debian GNU/Linux system but may be used by
others under the same license as 
.B sl 
itself.
