.TH SETMETAMODE 1 "09 Oct 1997" "Console tools" "Linux User's Manual"

.SH NAME
setmetamode \- define the keyboard meta key handling

.SH SYNOPSIS
.BI "setmetamode [ " meta | bit | metabit " | " esc | prefix | escprefix " ]"
.IX "setmetamode command" "" "\fLsetmetamode\fR command"  

.SH DESCRIPTION
.PP
Without argument,
.B setmetamode
prints the current Meta key mode.
With argument, it sets the Meta key mode as indicated.
The setting before and after the change are reported.
.LP
The Meta key mode is specific for each VT (and the VT
corresponding to stdin is used).

.SH OPTIONS
.TP
.I esc prefix escprefix
The Meta key sends an Escape prefix.
.TP
.I meta bit metabit
The Meta key sets the high order bit of the character.

.SH EXAMPLE

One might use
.B setmetamode
in an
.I /etc/rc
script to define the initial state of the Meta key mode,
e.g. by

.RS
INITTY=/dev/tty[1\-8]
.br
for tty in $INITTY; do
.RS
setmetamode escprefix < $tty
.RE
done
.RE

.SH "SEE ALSO"
.BR loadkeys (1).

