.TH SL-H 6 "Apr 3, 2001"
.UC 5
.SH NAME
sl-h \- display animations aimed to entertain users who liked to see SL runs
on their screen.
.SH SYNOPSIS
.B sl-h
[
.B \-alFe
]
.SH DESCRIPTION
.B sl-h 
displays animations aimed to entertain users who like to see SL runs
on their screen. This is a slightly modified version of
.B sl
command, but it runs much long to please you very well :)
.SH OPTIONS
.TP
.B \-a
Some trouble happen! You'll feel pity for people who need help :-)
.TP
.B \-l
Display mini SL.
.TP
.B \-F
SL flys! (Do you know Japanese animation, "Galaxy Express 999" ?)
.TP
.B \-e
Allow interrupt by Ctrl+C (Default, as this is so heavy and violent).
.PP
.SH "SEE ALSO"
.BR ls (1)
.SH BUGS
It never shows contents of current directory.
.SH AUTHOR
.BR sl (6)
was written by Toyoda Masashi <toyoda@is.titech.ac.jp>.
The code in
.B sl-h
is taken from a patch which is distributed from 
http://www.linet.gr.jp/~izumi/sl/ and written by Izumi Tomonori 
<izumi@linet.gr.jp>.
This manual page was written by Brian Ristuccia <brianr@debian.org>
and Kenshi Muto <kmuto@debian.org> for the Debian GNU/Linux system
but may be used by others under the same license as
.BR sl (6)
itself.
